name: build
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Buildozer Master
        run: |
          sudo apt-get update
          sudo apt-get install -y zip unzip libffi-dev libssl-dev libltdl-dev
          pip install --upgrade pip
          pip install cython==0.29.36
          pip install https://github.com/kivy/buildozer/archive/master.zip
          pip install https://github.com/kivy/python-for-android/archive/master.zip

      - name: Fix sdkmanager path (yehi main fix hai)
        run: |
          mkdir -p ~/.buildozer/android/platform/android-sdk/tools/bin
          mkdir -p ~/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin
          # GitHub ka sdkmanager ko buildozer wale folder me copy karo
          cp -r $ANDROID_HOME/cmdline-tools/latest/* ~/.buildozer/android/platform/android-sdk/cmdline-tools/latest/ || true
          ln -sf $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager ~/.buildozer/android/platform/android-sdk/tools/bin/sdkmanager
          ln -sf $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager ~/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin/sdkmanager
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses || true

      - name: Build APK
        run: |
          rm -rf bin
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: bin/*.apk
