name: build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v5

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK - License Fix
        uses: android-actions/setup-android@v3

      - name: Install Build-Tools 37 and Accept License
        run: |
          sdkmanager --install "build-tools;37.0.0" "build-tools;33.0.2" "platforms;android-33" "platform-tools"
          yes | sdkmanager --licenses

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.10'

      - name: Install Python Dependencies
        run: |
          sudo apt update
          sudo apt install -y zip unzip aidl
          pip install --upgrade pip
          pip install buildozer==1.5.0 kivy cython

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload Samundar APK
        uses: actions/upload-artifact@v5
        with:
          name: Samundar-APK
          path: bin/*.apk
